r_sho_pitch:
  ID: 1
  Return_Delay_Time: 0
l_sho_pitch:
  ID: 2
  Return_Delay_Time: 0
r_sho_roll:
  ID: 3
  Return_Delay_Time: 0
l_sho_roll:
  ID: 4
  Return_Delay_Time: 0
r_el:
  ID: 5
  Return_Delay_Time: 0
l_el:
  ID: 6
  Return_Delay_Time: 0
r_hip_yaw:
  ID: 7
  Return_Delay_Time: 0
l_hip_yaw:
  ID: 8
  Return_Delay_Time: 0
r_hip_roll:
  ID: 9
  Return_Delay_Time: 0
l_hip_roll:
  ID: 10
  Return_Delay_Time: 0
r_hip_pitch:
  ID: 11
  Return_Delay_Time: 0
l_hip_pitch:
  ID: 12
  Return_Delay_Time: 0
r_knee:
  ID: 13
  Return_Delay_Time: 0
l_knee:
  ID: 14
  Return_Delay_Time: 0
r_ank_pitch:
  ID: 15
  Return_Delay_Time: 0
l_ank_pitch:
  ID: 16
  Return_Delay_Time: 0
r_ank_roll:
  ID: 17
  Return_Delay_Time: 0
l_ank_roll:
  ID: 18
  Return_Delay_Time: 0
head_pan:
  ID: 19
  Return_Delay_Time: 0
head_tilt:
  ID: 20
  Return_Delay_Time: 0
